/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Malindu
 */import java.sql.*;
 import javax.swing.*;
public class menu extends javax.swing.JFrame {
    myConnection mycon;
    Connection conn;
    

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenu2 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jMenu2.setText("jMenu2");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane4.setPreferredSize(new java.awt.Dimension(190, 226));

        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Title");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(190, 50, 67, 32);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(280, 50, 155, 32);

        jButton2.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(319, 106, 81, 41);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umbrella-bg.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(0, 0, 680, 210);

        jTabbedPane4.addTab("Book", jPanel3);

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Publisher Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(150, 50, 108, 32);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(280, 50, 155, 32);

        jButton1.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(319, 106, 81, 41);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umbrella-bg.jpg"))); // NOI18N
        jLabel11.setText("jLabel9");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(0, 0, 680, 210);

        jTabbedPane4.addTab("Publisher", jPanel2);

        jPanel1.setLayout(null);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(280, 50, 155, 32);

        jLabel7.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Member Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(160, 50, 100, 32);

        jButton4.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(319, 106, 81, 41);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umbrella-bg.jpg"))); // NOI18N
        jLabel12.setText("jLabel9");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 680, 210);

        jTabbedPane4.addTab("Member", jPanel1);

        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Member ID");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(180, 50, 75, 32);
        jPanel4.add(jTextField3);
        jTextField3.setBounds(280, 50, 155, 32);

        jButton3.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(319, 106, 81, 41);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umbrella-bg.jpg"))); // NOI18N
        jLabel13.setText("jLabel9");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(0, 0, 680, 210);

        jTabbedPane4.addTab("Mobile", jPanel4);

        getContentPane().add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 680, 240));

        jLabel6.setFont(new java.awt.Font("Tunga", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                          Search Database");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umbrella-bg.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 110));

        jMenu1.setText("Manage");

        jMenuItem1.setText("Books ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Members");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Publishers");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Mobile Numbers");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Help");

        jMenuItem5.setText("About");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
     Member_register A=new Member_register();
    A.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    book_register A=new book_register();
    A.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       Publisher_register A=new Publisher_register();
        A.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Mobile_register A=new Mobile_register();
        A.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mycon=new myConnection();
        conn=mycon.getConnection();
        try{
            Statement st;
            st=conn.createStatement();
            ResultSet rs;
            String tt;
            tt=jTextField1.getText();
            rs = st.executeQuery("select * from publisher where p_name='"+tt+"'");
            if ( rs.next() ) {
                String name = rs.getString("p_name");
                String ID = rs.getString("p_id");
                String address=rs.getString("p_address");
                {JOptionPane.showMessageDialog(rootPane,"PUBLISHER ID - "+ID+"\n"+"PUBLISHER ADDRESS - "+address,"Found Result For-"+name,JOptionPane.INFORMATION_MESSAGE);}
            } else{ JOptionPane.showMessageDialog(rootPane, "NO DATA FOR THIS NAME");}
            conn.close();

        }catch(SQLException e)
        {System.out.print(e.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mycon=new myConnection();
        conn=mycon.getConnection();
        try{
            Statement st;
            st=conn.createStatement();
            ResultSet rs;
            String tt; 
             tt=jTextField2.getText();
              rs = st.executeQuery("select * from book where title='"+tt+"'");
               if ( rs.next() ) {
               String title = rs.getString("title");
                String ID = rs.getString("b_id");
                String author=rs.getString("author");
                String price=rs.getString("price");
              {JOptionPane.showMessageDialog(rootPane,"BOOK ID - "+ID+"\n"+"BOOK TITLE - "+title+"\n"+"BOOK AUTHOR - "+author+"\n"+"BOOK PRICE - "+price,"Found Result For-"+title,JOptionPane.INFORMATION_MESSAGE);}  
             } else{ JOptionPane.showMessageDialog(rootPane, "NO DATA FOR THIS NAME");}
                      conn.close();

        }catch(SQLException e)
        {System.out.print(e.getMessage());}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           mycon=new myConnection();
           conn=mycon.getConnection();
           try{
                 Statement st;
            st=conn.createStatement();
            ResultSet rs;
            String tt; 
             tt=jTextField3.getText();
              rs = st.executeQuery("select * from mobile where m_id='"+tt+"'");
                if ( rs.next() ) {
                    String id=rs.getString("m_id");
                    String num=rs.getString("m_number");
                    {JOptionPane.showMessageDialog(rootPane,"MEMBER ID - "+id+"\n"+"MOBILE NUMBER - "+num,"Found Result For-"+id,JOptionPane.INFORMATION_MESSAGE);}
                      } else{ JOptionPane.showMessageDialog(rootPane, "NO DATA FOR THIS NAME");}
                conn.close();
                    
                }catch(SQLException e)
               {System.out.print(e.getMessage());}
           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   mycon=new myConnection();
           conn=mycon.getConnection();
           try{
                 Statement st;
            st=conn.createStatement();
            ResultSet rs;
            String tt; 
             tt=jTextField4.getText();  
               rs = st.executeQuery("select * from member where name='"+tt+"'");
                if ( rs.next() ) {
                    String id=rs.getString("m_id");
                    String name=rs.getString("name");
                    String address=rs.getString("address");
                    String exp=rs.getString("exp_date");
                    {JOptionPane.showMessageDialog(rootPane,"MEMBER ID - "+id+"\n"+"MEMBER NAME - "+name+"\n"+"MEMBER ADDRESS - "+address+"\n"+"EXPIRE DATE - "+exp,"Found Result For-"+name,JOptionPane.INFORMATION_MESSAGE);} 
                   } else{ JOptionPane.showMessageDialog(rootPane, "NO DATA FOR THIS NAME");}
                 conn.close();
                }catch(SQLException e)
                     {System.out.print(e.getMessage());}
                           
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
      help a=new help();
      a.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
